### ISSUE TITLE
No module named 'cupy.core'

### ISSUE THREAD

**Issue by busrauludag1** [chainer/google-colaboratory#10]
I try to use below script (as you said your README.md file) to solve this 'No module named copy.core' error on **Colab**.

`!curl https://colab.chainer.org/install | CHAINER_VERSION="==5.1.0" CUPY_VERSION="==5.1.0" sh -`

But it doesn't work and I got this message 

<img width="906" alt="cupy error" src="https://user-images.githubusercontent.com/51692429/196900473-31b00ee6-6965-4830-927e-dfc0e9182f32.png">

I couldn't install cupy in a correct way. Are there anyone who have any idea about this message and solution? Could you help me ASAP please?

Thanks in advance.

**Comment by kmaehashi** [comment]
Hi, this scirpt no longer supports the latest Colab environment. You can just use `pip install chainer` if you need.
Please note that Chainer is no longer actively maintained and not recommended for new projects.
https://chainer.org/announcement/2019/12/05/released-v7.html

**Comment by busrauludag1** [comment]
Ok, thank you so much for your answer @kmaehashi. I was trying to run an old project which requires CuPy. But installing chainer doesn't work on Colab. I still get the same error **No module named 'cupy.core'**
